[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes pkg-config build-essential libusb-1.0-0:$CROSS_DEB_ARCH  libusb-1.0-0-dev:$CROSS_DEB_ARCH",
]
env.passthrough = [
    "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig",
    "PKG_CONFIG_ALLOW_CROSS=true",
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes pkg-config build-essential libusb-1.0-0:$CROSS_DEB_ARCH  libusb-1.0-0-dev:$CROSS_DEB_ARCH",
]
env.passthrough = [
    "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig",
    "PKG_CONFIG_ALLOW_CROSS=true",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes pkg-config build-essential libusb-1.0-0  libusb-1.0-0-dev",
]
env.passthrough = [
    "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-musl/pkgconfig",
    "PKG_CONFIG_ALLOW_CROSS=true",
    "PKG_CONFIG_ALL_STATIC=true",
    # "PKG_CONFIG_PATH_x86_64_unknown_linux_musl=/usr/lib/pkgconfig",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes pkg-config build-essential libusb-1.0-0:$CROSS_DEB_ARCH  libusb-1.0-0-dev:$CROSS_DEB_ARCH",
]
