[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

#[target.armv7-unknown-linux-gnueabihf]
#linker = "gcc-sysroot"
#strip = { path = "arm-linux-gnueabihf-strip" }
#objcopy = { path = "arm-linux-gnueabihf-objcopy" }

[target.armv7-unknown-linux-gnueabihf]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--target=armv7-unknown-linux-gnueabihf",
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--target=x86_64-unknown-linux-musl",
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--target=aarch64-unknown-linux-gnu",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--target=x86_64-unknown-linux-gnu",
]
