[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.armv7-unknown-linux-gnueabihf]
linker = "gcc-sysroot"
strip = { path = "arm-linux-gnueabihf-strip" }
objcopy = { path = "arm-linux-gnueabihf-objcopy" }

# Linker options for MUSL targets. We need to manually specify --target as cargo
# doesn't do that for us by default
[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--target=x86_64-unknown-linux-musl",
]

[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--target=aarch64-unknown-linux-musl",
]
