[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]


#[target.arm-unknown-linux-gnueabihf]
#linker = "gcc-sysroot"
#strip = { path = "arm-linux-gnueabihf-strip" }
#objcopy = { path = "arm-linux-gnueabihf-objcopy" }

#[target.aarch64-unknown-linux-gnu]
#rustflags = ["-Ctarget-feature=+crt-static"]


#[target.armv7-unknown-linux-gnueabihf]
#rustflags = ["-Ctarget-feature=+crt-static"]
