FROM rustembedded/cross:armv7-unknown-linux-gnueabihf
## Remove any existing non armhf libusb
RUN apt-get update && apt-get remove libusb-1.0-0 libusb-1.0-0-dev
RUN dpkg --add-architecture armhf && apt-get update && apt-get install -y libhidapi-dev:armhf libudev-dev:armhf libusb-1.0-0:armhf libusb-1.0-0-dev:armhf pkg-config
ENV PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
RUN ldconfig
ENV RUSTFLAGS='-L /lib/arm-linux-gnueabihf'