name: Tests

on:
  push:
    branches:    
      - '**'

env:
  CARGO_TERM_COLOR: always
jobs:
  rust_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Install native packages
        run: sudo apt-get install libhidapi-dev libhidapi-libusb0 libusb-1.0-0 libusb-1.0-0-dev

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings
      
      - name: Tests
        run: cargo test --all

